name: firebase_flutter
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 


flutter_native_splash:
  color: "#f7f6f1"
  color_dark: "#272727"
  image: assets/images/lgpl.jpg
  image_dark: assets/images/lgpl.jpg

  android_12:
    image: assets/images/lgpl.jpg
    icon_background_color: "#f7f6f1"
    icon_background_color_dark: "#272727"
    image_dark: assets/images/lgpl.jpg


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/logo/
    - assets/videos/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
