// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbEFtI8-YSNBEdhYmW-9N1wH6OrOOUwEM',
    appId: '1:729989222510:web:8ac4051b5b402d7417567f',
    messagingSenderId: '729989222510',
    projectId: 'flutterfirebaseauthentic-7ee3d',
    authDomain: 'flutterfirebaseauthentic-7ee3d.firebaseapp.com',
    storageBucket: 'flutterfirebaseauthentic-7ee3d.firebasestorage.app',
    measurementId: 'G-E1VJ6P7YNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7JJNM2RErKvk64UA8mMIk-Dhznf8XgoM',
    appId: '1:729989222510:android:397b7f0ed8b5cbe117567f',
    messagingSenderId: '729989222510',
    projectId: 'flutterfirebaseauthentic-7ee3d',
    storageBucket: 'flutterfirebaseauthentic-7ee3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCghLwsYUYQc0KhKr7pDe1HYVWkyvJDuSE',
    appId: '1:729989222510:ios:91b61f6c577d208817567f',
    messagingSenderId: '729989222510',
    projectId: 'flutterfirebaseauthentic-7ee3d',
    storageBucket: 'flutterfirebaseauthentic-7ee3d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCghLwsYUYQc0KhKr7pDe1HYVWkyvJDuSE',
    appId: '1:729989222510:ios:91b61f6c577d208817567f',
    messagingSenderId: '729989222510',
    projectId: 'flutterfirebaseauthentic-7ee3d',
    storageBucket: 'flutterfirebaseauthentic-7ee3d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFlutter',
  );
}
